cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap "caskroom/fonts"

cask 'font-fira-code'
cask 'hyper'
cask 'sizeup'
cask 'istat-menus'
cask 'launchbar'
cask '1password'
cask '1password-cli'
cask 'dash'
cask 'sublime-text'
cask 'iterm2'
cask 'adium'
cask 'atom'
cask 'visual-studio-code'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'transmit'
cask 'fantastical'
cask 'xquartz'
cask 'paw'
cask 'tower'

brew 'nmap'
brew 'tmux'
brew 'vim'
brew 'macvim'
brew 'neovim'
brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
