" ----------
" Vim Config
" ----------
"
" TL;DR
" Run install.sh to symlink this file to your home directory (e.g. $HOME/.vimrc)
"
" How this works:
"
" This file is minimal.  Most of the vim settings and initialization is in
" several files in .vim/init.  This makes it easier to find things and to
" merge between branches and repos.
"
" Please do not add configuration to this file, unless it *really* needs to
" come first or last, like vundle. Instead, add it to one of the files in
" .vim/init, or create a new one.

set nocompatible                " Don't maintain compatibility with vi
filetype off
syntax on

" Vundle stuff
set rtp+=~/.vim/bundle/vundle/
set rtp+=/usr/local/opt/fzf
call vundle#rc()

Plugin 'tobyS/vmustache'
Plugin 'FooSoft/vim-argwrap'
Plugin 'sheerun/vim-polyglot'
Plugin 'gmarik/vundle'
Plugin 'w0rp/ale'
Plugin 'joshdick/onedark.vim'
Plugin 'nelstrom/vim-qargs.git'
Plugin 'tpope/vim-fugitive.git'
Plugin 'tpope/vim-cucumber.git'
Plugin 'tpope/vim-haml.git'
Plugin 'tpope/vim-endwise.git'
Plugin 'tpope/vim-surround.git'
Plugin 'scrooloose/nerdtree.git'
Plugin 'scrooloose/nerdcommenter.git'
Plugin 'mileszs/ack.vim.git'
Plugin 'tpope/vim-repeat.git'
Plugin 'plasticboy/vim-markdown.git'
Plugin 'tpope/vim-unimpaired.git'
Plugin 'godlygeek/tabular.git'
Plugin 'ervandew/supertab.git'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'itchyny/lightline.vim'
Plugin 'vim-scripts/matchit.zip'
Plugin 'benmills/vimux'
Plugin 'rizzatti/dash.vim'

Plugin 'phpactor/phpactor'
" Snippets
Plugin 'mattn/emmet-vim'
Plugin 'SirVer/ultisnips'
Plugin 'isRuslan/vim-es6'
Plugin 'honza/vim-snippets'

Plugin 'tobyS/pdv'

Plugin 'shougo/deoplete.nvim'

if !has('nvim')
  Plugin 'roxma/nvim-yarp'
  Plugin 'roxma/vim-hug-neovim-rpc'
endif

Plugin 'junegunn/fzf.vim'

filetype plugin indent on

let g:python2_host_prog = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'

" Source initialization files
runtime! init/**.vim
